#!/usr/bin/env bash

trap ctrl_c INT
UNIT=$1

function ctrl_c() {
  echo "Resuming $UNIT"
  systemctl start $UNIT
  exit 0
}

(
  echo "Suspending $1"
  systemctl stop $1

  echo "Waiting for $2"
  sleep $2
)

echo "Resuming $1"
systemctl start $1
